[package]
name = "chat-room"
version = "0.1.0"
authors = ["ouwenkg <2630582710@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.10.1"
url = "2.1.1"